### ISSUE TITLE
Doesn't compile on GNU/Linux

### ISSUE THREAD

**Issue by ghost** [pfaucon/PBSIM-PacBio-Simulator#3]
Hello,

I've tried to compile `pbsim` under GNU/Linux x86_64 using the command `autoreconf -fiv ; ./configure ; make` but it doesn't work.

At first, `make` fail because of missing `NEWS` and `README` file.
[First output can be seen here.](http://pastebin.com/raw/uLujAJuX)

The workaround that is to do `touch NEWS ; touch README` before `make`.

Still, `make` fails to compile.
[Second output can be seen here.](http://pastebin.com/raw/DYEuRz9V)

**Comment by lpryszcz** [comment]
same here... any solution?

**Comment by pfaucon** [comment]
Sorry, I wasn't watching this repo but i added a new script in src, make_script.sh.  It's not a standard, but I'm not well versed in the autoconfig it looks like the the autogenerated make file includes pbsim.o but not the other object files.

EDIT: if you are interested in making a more reasonable solution please feel free to make a pull request and I can pull it in.
